### ISSUE TITLE
Sanparks FGDC upload does not accept data files

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1030]
---

Author Name: **ben leinfelder** (ben leinfelder)
Original Redmine Issue: 6517, https://projects.ecoinformatics.org/ecoinfo/issues/6517
Original Date: 2014-04-15
Original Assignee: ben leinfelder

---

> Hi Ben
> Soorry its me again. Im trying to upload FGDC data into dataknp and it  doesnt seem to be working. If I add a zip file I get and error saying cant add multipart data when I don’t attach data the metadata uploads but I cant seem to see the data even when I have added the correct keywords. Im attaching the xml data that im trying to add and the one that uploaded was Judith_kruger .88.1. Im also attaching the zip file
> Thanks
> J

When uploading a sample FGDC file with a shp data file, I get this error:
```
edu.ucsb.nceas.metacat.client.MetacatException: <?xml version="1.0"?>
<error>
Error: problem reading multipart data: Corrupt form data: premature ending
</error>

	at edu.ucsb.nceas.metacat.client.MetacatClient.upload(MetacatClient.java:716)
	at edu.ucsb.nceas.metacat.clientview.ClientViewHelper.handlePackageUpload(ClientViewHelper.java:473)
	at edu.ucsb.nceas.metacat.clientview.ClientViewHelper.handleClientRequest(ClientViewHelper.java:290)
	at edu.ucsb.nceas.metacat.clientview.ClientViewHelper.clientRequest(ClientViewHelper.java:200)
	at org.apache.jsp.style.skins.sanparks.SaeonUpload_jspx._jspService(SaeonUpload_jspx.java:108)

```

I've looked into it and it appears to be an issue with sending "chunked" data because we don't know how big the input stream is. (Transfer-Encoding: chunked).

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2014-04-24T23:20:21Z

---

Switched to use Apache's FileUpload library and can now handle the chunked streaming uploads. Added a test for this scenario to the existing suite.
