### ISSUE TITLE
Metacat indexing the resource map prior to metadata document

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1032]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 6520, https://projects.ecoinformatics.org/ecoinfo/issues/6520
Original Date: 2014-04-17
Original Assignee: ben leinfelder

---

When I tested the metacat replication, I got the error in the remote server  when i used morpho 1.10 or online registry to insert a package with data file to the local metacat:

metacat-index 20140417-15:11:18: [ERROR]: Solr index doesn't have the information about the id tao.13007.1 which is a component in the resource map resourceMap_tao.13007.1. Metacat-Index can't process the resource map prior to its components. [edu.ucsb.nceas.metacat.index.SolrIndex]
edu.ucsb.nceas.metacat.index.resourcemap.ResourceMapException: Solr index doesn't have the information about the id tao.13007.1 which is a component in the resource map resourceMap_tao.13007.1. Metacat-Index can't process the resource map prior to its components.
	at edu.ucsb.nceas.metacat.index.resourcemap.ResourceMapSubprocessor.getSolrDocs(ResourceMapSubprocessor.java:118)
	at edu.ucsb.nceas.metacat.index.resourcemap.ResourceMapSubprocessor.processResourceMap(ResourceMapSubprocessor.java:95)
	at edu.ucsb.nceas.metacat.index.resourcemap.ResourceMapSubprocessor.processDocument(ResourceMapSubprocessor.java:81)
	at edu.ucsb.nceas.metacat.index.SolrIndex.process(SolrIndex.java:216)
	at edu.ucsb.nceas.metacat.index.SolrIndex.insert(SolrIndex.java:364)
	at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:557)
	at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:514)
	at edu.ucsb.nceas.metacat.index.SystemMetadataEventListener.entryUpdated(SystemMetadataEventListener.java:146)
	at edu.ucsb.nceas.metacat.index.SystemMetadataEventListener.entryAdded(SystemMetadataEventListener.java:119)
	at com.hazelcast.client.impl.EntryListenerManager.notifyListeners(EntryListenerManager.java:148)
	at com.hazelcast.client.impl.EntryListenerManager.notifyListeners(EntryListenerManager.java:130)
	at com.hazelcast.client.impl.ListenerManager.customRun(ListenerManager.java:88)
	at com.hazelcast.client.ClientRunnable.run(ClientRunnable.java:30)
	at java.lang.Thread.run(Thread.java:744)

But the in the local host, the solr index worked fine.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Jing Tao** (Jing Tao)
Original Date: 2014-04-22T20:30:28Z

---

Actually, the localhost has the same error:
[ERROR]: Solr index doesn't have the information about the id tao.13010.1 which is a component in the resource map resourceMap_tao.13010.1. Metacat-Index can't process the resource map prior to its components. [edu.ucsb.nceas.metacat.index.SolrIndex]
edu.ucsb.nceas.metacat.index.resourcemap.ResourceMapException: Solr index doesn't have the information about the id tao.13010.1 which is a component in the resource map resourceMap_tao.13010.1. Metacat-Index can't process the resource map prior to its components.
	at edu.ucsb.nceas.metacat.index.resourcemap.ResourceMapSubprocessor.getSolrDocs(ResourceMapSubprocessor.java:118)
	at edu.ucsb.nceas.metacat.index.resourcemap.ResourceMapSubprocessor.processResourceMap(ResourceMapSubprocessor.java:95)
	at edu.ucsb.nceas.metacat.index.resourcemap.ResourceMapSubprocessor.processDocument(ResourceMapSubprocessor.java:81)
	at edu.ucsb.nceas.metacat.index.SolrIndex.process(SolrIndex.java:216)
	at edu.ucsb.nceas.metacat.index.SolrIndex.insert(SolrIndex.java:364)
	at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:557)
	at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:514)
	at edu.ucsb.nceas.metacat.index.SystemMetadataEventListener.entryUpdated(SystemMetadataEventListener.java:146)
	at edu.ucsb.nceas.metacat.index.SystemMetadataEventListener.entryAdded(SystemMetadataEventListener.java:119)
	at com.hazelcast.client.impl.EntryListenerManager.notifyListeners(EntryListenerManager.java:148)
	at com.hazelcast.client.impl.EntryListenerManager.notifyListeners(EntryListenerManager.java:130)
	at com.hazelcast.client.impl.ListenerManager.customRun(ListenerManager.java:88)
	at com.hazelcast.client.ClientRunnable.run(ClientRunnable.java:30)
	at java.lang.Thread.run(Thread.java:744)

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Jing Tao** (Jing Tao)
Original Date: 2014-04-22T20:31:27Z

---

I also saw the error when i used morpho 1.10 to insert a package with data:
[ERROR]: org.apache.solr.common.SolrException: org.apache.lucene.queryParser.ParseException: Cannot parse 'resourceMap:*+id:"tao.13010.1"': Encountered " ":" ": "" at line 1, column 16.
Was expecting one of:
    <EOF> 
    <AND> ...
    <OR> ...
    <NOT> ...
    "+" ...
    "-" ...
    "(" ...
    "*" ...
    "^" ...
    <QUOTED> ...
    <TERM> ...
    <FUZZY_SLOP> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:105)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:173)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:1368)
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:140)
	at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:89)
	at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:118)
	at edu.ucsb.nceas.metacat.common.query.EmbeddedSolrQueryService.query(EmbeddedSolrQueryService.java:122)
	at edu.ucsb.nceas.metacat.common.query.SolrQueryServiceController.query(SolrQueryServiceController.java:110)
	at edu.ucsb.nceas.metacat.index.MetacatSolrIndex.query(MetacatSolrIndex.java:135)
	at edu.ucsb.nceas.metacat.dataone.MNodeService.query(MNodeService.java:1631)
	at edu.ucsb.nceas.metacat.dataone.MNodeService.lookupOreFor(MNodeService.java:1856)
	at edu.ucsb.nceas.metacat.dataone.SystemMetadataFactory.oreExistsFor(SystemMetadataFactory.java:617)
	at edu.ucsb.nceas.metacat.dataone.SystemMetadataFactory.createSystemMetadata(SystemMetadataFactory.java:524)
	at edu.ucsb.nceas.metacat.MetacatHandler.handleInsertOrUpdateAction(MetacatHandler.java:1843)
	at edu.ucsb.nceas.metacat.MetaCatServlet.handleGetOrPost(MetaCatServlet.java:906)
	at edu.ucsb.nceas.metacat.MetaCatServlet.doPost(MetaCatServlet.java:503)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2014-04-22T22:39:50Z

---

Now we will submit the ORE for indexing after we are sure the metadata document has been indexed.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2014-04-23T17:45:00Z

---

Tested package upload from Morpho and the resourceMap was successfully indexed.
