### ISSUE TITLE
Solr query used for ORE lookup in Metacat has a syntax issue

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1034]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 6529, https://projects.ecoinformatics.org/ecoinfo/issues/6529
Original Date: 2014-04-22
Original Assignee: ben leinfelder

---

I also saw the error when i used morpho 1.10 to insert a package with data:
[ERROR]: org.apache.solr.common.SolrException: org.apache.lucene.queryParser.ParseException: Cannot parse 'resourceMap:*+id:"tao.13010.1"': Encountered " ":" ": "" at line 1, column 16.
Was expecting one of:
<EOF> 
<AND> ...
<OR> ...
<NOT> ...
"+" ...
"-" ...
"(" ...
"*" ...
"^" ...
<QUOTED> ...
<TERM> ...
<FUZZY_SLOP> ...
<PREFIXTERM> ...
<WILDTERM> ...
"[" ...
"{" ...
<NUMBER> ...

at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:105)
    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:173)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:1368)
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:140)
    at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:89)
    at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:118)
    at edu.ucsb.nceas.metacat.common.query.EmbeddedSolrQueryService.query(EmbeddedSolrQueryService.java:122)
    at edu.ucsb.nceas.metacat.common.query.SolrQueryServiceController.query(SolrQueryServiceController.java:110)
    at edu.ucsb.nceas.metacat.index.MetacatSolrIndex.query(MetacatSolrIndex.java:135)
    at edu.ucsb.nceas.metacat.dataone.MNodeService.query(MNodeService.java:1631)
    at edu.ucsb.nceas.metacat.dataone.MNodeService.lookupOreFor(MNodeService.java:1856)
    at edu.ucsb.nceas.metacat.dataone.SystemMetadataFactory.oreExistsFor(SystemMetadataFactory.java:617)
    at edu.ucsb.nceas.metacat.dataone.SystemMetadataFactory.createSystemMetadata(SystemMetadataFactory.java:524)
    at edu.ucsb.nceas.metacat.MetacatHandler.handleInsertOrUpdateAction(MetacatHandler.java:1843)
    at edu.ucsb.nceas.metacat.MetaCatServlet.handleGetOrPost(MetaCatServlet.java:906)
    at edu.ucsb.nceas.metacat.MetaCatServlet.doPost(MetaCatServlet.java:503)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2014-04-22T22:33:06Z

---

I can see this happening on the KNB. Metacat is querying itself (solr index) to find potential OREs and seems there's a syntax issue. Will investigate further.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2014-04-23T17:20:27Z

---

Corrected the syntax in trunk and added an additional JUnit assertion to the ORE package test that already existed.
