### ISSUE TITLE
resourceMap field is not indexed 

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1052]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 6595, https://projects.ecoinformatics.org/ecoinfo/issues/6595
Original Date: 2014-09-12
Original Assignee: Lauren Walker

---

See some error like;
metacat-index 20140912-14:16:31: [ERROR]: <http://resourceMap_tao.13083.2> Code: 11/LOWERCASE_PREFERRED in HOST: lowercase is preferred in this component [edu.ucsb.nceas.metacat.index.SolrIndex]
org.apache.jena.riot.RiotException: <http://resourceMap_tao.13083.2> Code: 11/LOWERCASE_PREFERRED in HOST: lowercase is preferred in this component
	at org.apache.jena.riot.system.IRIResolver.exceptions(IRIResolver.java:309)
	at org.apache.jena.riot.system.IRIResolver.access$000(IRIResolver.java:31)
	at org.apache.jena.riot.system.IRIResolver$IRIResolverNormal.resolve(IRIResolver.java:414)
	at org.apache.jena.riot.system.IRIResolver.resolveIRI(IRIResolver.java:184)
	at org.apache.jena.riot.system.IRIResolver.resolveString(IRIResolver.java:175)
	at org.apache.jena.riot.RiotReader.createParser(RiotReader.java:127)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTFactoryImpl$1.read(RDFParserRegistry.java:141)
	at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:818)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:258)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:244)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:69)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:241)
	at com.hp.hpl.jena.ontology.impl.OntModelImpl.read(OntModelImpl.java:2148)
	at edu.ucsb.nceas.metacat.index.annotation.RdfXmlSubprocessor.process(RdfXmlSubprocessor.java:146)
	at edu.ucsb.nceas.metacat.index.annotation.RdfXmlSubprocessor.processDocument(RdfXmlSubprocessor.java:107)
	at edu.ucsb.nceas.metacat.index.SolrIndex.process(SolrIndex.java:216)
	at edu.ucsb.nceas.metacat.index.SolrIndex.insert(SolrIndex.java:364)
	at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:562)
	at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:519)
	at edu.ucsb.nceas.metacat.index.SystemMetadataEventListener.entryUpdated(SystemMetadataEventListener.java:146)
	at edu.ucsb.nceas.metacat.index.SystemMetadataEventListener.entryAdded(SystemMetadataEventListener.java:119)
	at com.hazelcast.client.impl.EntryListenerManager.notifyListeners(EntryListenerManager.java:148)
	at com.hazelcast.client.impl.EntryListenerManager.notifyListeners(EntryListenerManager.java:130)
	at com.hazelcast.client.impl.ListenerManager.customRun(ListenerManager.java:88)
	at com.hazelcast.client.ClientRunnable.run(ClientRunnable.java:30)
	at java.lang.Thread.run(Thread.java:722)

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Lauren Walker** (Lauren Walker)
Original Date: 2014-09-15T21:36:55Z

---

This is referring to the triple model/graph name, which is sometimes a URI starting with http://. They are now created with all lowercase letters.
