### ISSUE TITLE
Can't index resource in Metacat trunk

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1054]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 6610, https://projects.ecoinformatics.org/ecoinfo/issues/6610
Original Date: 2014-10-10
Original Assignee: Lauren Walker

---

metacat-index 20141010-16:51:45: [ERROR]: SolrIndex.update - could not update the solr index since Illegal character in scheme name at index 11: resourceMap_urn:uuid:f6fe65e9-8603-4005-893b-05c6e58a7ac5 [edu.ucsb.nceas.metacat.index.SolrIndex]
org.apache.solr.client.solrj.SolrServerException: Illegal character in scheme name at index 11: resourceMap_urn:uuid:f6fe65e9-8603-4005-893b-05c6e58a7ac5
	at edu.ucsb.nceas.metacat.index.SolrIndex.process(SolrIndex.java:223)
	at edu.ucsb.nceas.metacat.index.SolrIndex.insert(SolrIndex.java:367)
	at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:575)
	at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:528)
	at edu.ucsb.nceas.metacat.index.SystemMetadataEventListener.entryUpdated(SystemMetadataEventListener.java:146)
	at com.hazelcast.client.impl.EntryListenerManager.notifyListeners(EntryListenerManager.java:153)
	at com.hazelcast.client.impl.EntryListenerManager.notifyListeners(EntryListenerManager.java:130)
	at com.hazelcast.client.impl.ListenerManager.customRun(ListenerManager.java:88)
	at com.hazelcast.client.ClientRunnable.run(ClientRunnable.java:30)
	at java.lang.Thread.run(Thread.java:722)

I remember Lauren fixed issue. But I am not sure why it comes back again.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Jing Tao** (Jing Tao)
Original Date: 2016-01-13T23:04:49Z

---

I just confirmed that the bug was fixed.
