### ISSUE TITLE
Exception when a user create an account in the file authentication mechanism

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1082]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 6756, https://projects.ecoinformatics.org/ecoinfo/issues/6756
Original Date: 2015-05-07
Original Assignee: Jing Tao

---

Andrei report this issue on Metacat trunk:

On 4/28/15 12:05 PM, Andrei Buium wrote:
> Hi Jing,
> I'm still running into problems with the password file. Maybe you can clear up what I need to do.
>
> I editted the password.xml file manually, but got stuck on the password hash part.
> I did some googling on bcrypt (without finding any clear directions on how to just simply hash a password, as opposed to encrypting a file).
>
> Any advice on the above? Or... is it possible to leave the user without a password?
> I saw this is a command that specifies no password:
> ./authFileManager.sh useradd -i -dn <user-distinguish-name>
>
> Unfortunately, running the following:
>
> /var/lib/tomcat7/webapps/metacat/WEB-INF/scripts/bash#     ./authFileManager.sh useradd -i -dn "uid=andreib,o=epscor,dc=unm,dc=edu"
>
>
> Gave me an exception:
>
> This script should be run at the directory of /tomcat-webapps/your-context/WEB-INF/WEB-INF/scripts/bash/.
> Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
> at edu.ucsb.nceas.metacat.properties.PropertyService.<clinit>(PropertyService.java:72)
> at edu.ucsb.nceas.metacat.authentication.AuthFile.main(AuthFile.java:636)
> Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
>

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Jing Tao** (Jing Tao)
Original Date: 2015-05-08T18:13:06Z

---

The jar file names were changed, so it threw the NoClassDefFoundError. Now the script use the wild card in the class path. The problem is resolved.
