### ISSUE TITLE
Uploading a resource map with provenance data causes an NPE during indexing

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1153]
---

Author Name: **Peter Slaughter** (Peter Slaughter)
Original Redmine Issue: 7161, https://projects.ecoinformatics.org/ecoinfo/issues/7161
Original Date: 2016-11-22
Original Assignee: Jing Tao

---

When uploading a resource map with provenance relationships included, indexing exits with an NPE during processing of RdfXmlSubprocessor:

Java.lang.NullPointerException
        at org.dataone.cn.indexer.annotation.RdfXmlSubprocessor.getSolrDocs(RdfXmlSubprocessor.java:278)
        at org.dataone.cn.indexer.annotation.RdfXmlSubprocessor.process(RdfXmlSubprocessor.java:265)
        at org.dataone.cn.indexer.annotation.RdfXmlSubprocessor.processDocument(RdfXmlSubprocessor.java:119)
...

The problem appears to be caused by RdfXmlSubprocessor.getSolrDocs() calling httpService, which causes the NPE because an http solr server
is not run on metacat member node instances, which rely on the embedded solr server instead.

The included files are the resource map that was uploaded that caused the NPE, and a portion of the tomcat log file that includes
indexer TRACE info and the NPE.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Jing Tao** (Jing Tao)
Original Date: 2016-12-01T20:39:59Z

---

Wrote a new MetacatRdfXmlSubprocessor which overwrites the code to access the solr http server directly. I also wrote a junit test class to test it and it worked well.
