### ISSUE TITLE
MN.updateSystemmetadata shouldn't call CN.synchronize if the synchronize is off on the MN

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1227]
Val reported this error:
```essdive_mn | metacat 20180316-17:25:27: [WARN]: registering ConnectionManager... [org.dataone.client.utils.HttpConnectionMonitorService:addMonitor:65]
essdive_mn | org.dataone.service.exceptions.ServiceFailure: Unexpected Exception in CN.synchronize: progress: null:: java.lang.NullPointerException
essdive_mn |     at org.dataone.service.util.ExceptionHandler.deserializeXml(ExceptionHandler.java:633)
essdive_mn |     at org.dataone.service.util.ExceptionHandler.deserializeXmlAndThrowException(ExceptionHandler.java:517)
essdive_mn |     at org.dataone.service.util.ExceptionHandler.deserializeAndThrowException(ExceptionHandler.java:363)
essdive_mn |     at org.dataone.service.util.ExceptionHandler.deserializeAndThrowException(ExceptionHandler.java:313)
essdive_mn |     at org.dataone.service.util.ExceptionHandler.filterErrors(ExceptionHandler.java:107)
essdive_mn |     at org.dataone.service.util.ExceptionHandler.filterErrors(ExceptionHandler.java:82)
essdive_mn |     at org.dataone.client.rest.HttpMultipartRestClient.doPostRequest(HttpMultipartRestClient.java:463)
essdive_mn |     at org.dataone.client.v2.impl.MultipartCNode.synchronize(MultipartCNode.java:701)
essdive_mn |     at edu.ucsb.nceas.metacat.dataone.MNodeService$1.run(MNodeService.java:2788)
essdive_mn |     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
essdive_mn |     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
essdive_mn |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
essdive_mn |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
essdive_mn |     at java.lang.Thread.run(Thread.java:748)
essdive_mn | metacat 20180316-17:25:27: [ERROR]: It is a DataONEBaseException and its detail code is 4961 and its code is 500 [edu.ucsb.nceas.metacat.dataone.MNodeService$1:run:2794]
essdive_mn | metacat 20180316-17:25:27: [ERROR]: Can't update the systemmetadata of pid ess-dive-3c465bbaa2f07a5-20180316T095659253957 in CNs through cn.synchronize method since Unexpected Exception in CN.synchronize: progress: null:: java.lang.NullPointerException [edu.ucsb.nceas.metacat.dataone.MNodeService$1:run:2795]
essdive_mn | org.dataone.service.exceptions.ServiceFailure: Unexpected Exception in CN.synchronize: progress: null:: java.lang.NullPointerException
essdive_mn |     at org.dataone.service.util.ExceptionHandler.deserializeXml(ExceptionHandler.java:633)
essdive_mn |     at org.dataone.service.util.ExceptionHandler.deserializeXmlAndThrowException(ExceptionHandler.java:517)
essdive_mn |     at org.dataone.service.util.ExceptionHandler.deserializeAndThrowException(ExceptionHandler.java:363)
essdive_mn |     at org.dataone.service.util.ExceptionHandler.deserializeAndThrowException(ExceptionHandler.java:313)
essdive_mn |     at org.dataone.service.util.ExceptionHandler.filterErrors(ExceptionHandler.java:107)
essdive_mn |     at org.dataone.service.util.ExceptionHandler.filterErrors(ExceptionHandler.java:82)
essdive_mn |     at org.dataone.client.rest.HttpMultipartRestClient.doPostRequest(HttpMultipartRestClient.java:463)
essdive_mn |     at org.dataone.client.v2.impl.MultipartCNode.synchronize(MultipartCNode.java:701)
essdive_mn |     at edu.ucsb.nceas.metacat.dataone.MNodeService$1.run(MNodeService.java:2788)
essdive_mn |     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
essdive_mn |     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
essdive_mn |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
essdive_mn |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
essdive_mn |     at java.lang.Thread.run(Thread.java:748)```


The property looks `dataone.nodeSynchronize=false`. So we should NOT call the cn.synchronize method in MN.updateSystemmetadata method.

**Comment by taojing2002** [comment]
I tested and found the exception only happens in dataone-unconfigured Metacat which the sync is off. By the way, the exception doesn't hurt anything but the log file :).

**Comment by taojing2002** [comment]
The code which will call the cn.synchronize method when the property dataone.nodeSynchronized is true was added.
