### ISSUE TITLE
Document the 2.10 index schema upgrade process

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacat#1349]
When upgrading Metacat for the Arctic Data Center, I assumed that the Metacat admin upgrade would also upgrade the Solr schema document in `/var/metacat/solr-home/conf/schema.xml` with the newly indexed fields.  After troubleshooting indexing issues with new content with the data team this week, I found all new index task entries in the log to be throwing this error:
```
metacat-index 20190421-11:50:09: [DEBUG]: SolrIndex.process - the object format id for the pid urn:uuid:6aa6aa22-00d0-4fe8-93e2-656478dfcdbf is application/octet-stream [edu.ucsb.nceas.metacat.index.SolrIndex:process:216]
metacat-index 20190421-11:50:09: [ERROR]: org.apache.solr.common.SolrException: ERROR: [doc=urn:uuid:6aa6aa22-00d0-4fe8-93e2-656478dfcdbf] unknown field 'archived'
        at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:340)
        at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:60)
        at org.apache.solr.handler.XMLLoader.processUpdate(XMLLoader.java:157)
        at org.apache.solr.handler.XMLLoader.load(XMLLoader.java:79)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:58)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1376)
        at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:142)
        at org.apache.solr.client.solrj.request.AbstractUpdateRequest.process(AbstractUpdateRequest.java:105)
        at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:121)
        at org.apache.solr.client.solrj.SolrServer.add(SolrServer.java:106)
        at edu.ucsb.nceas.metacat.index.SolrIndex.insertToIndex(SolrIndex.java:546)
        at edu.ucsb.nceas.metacat.index.SolrIndex.insert(SolrIndex.java:434)
        at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:644)
        at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:598)
        at edu.ucsb.nceas.metacat.index.SystemMetadataEventListener.entryUpdated(SystemMetadataEventListener.java:149)
        at edu.ucsb.nceas.metacat.index.SystemMetadataEventListener.entryAdded(SystemMetadataEventListener.java:119)
        at com.hazelcast.client.impl.EntryListenerManager.notifyListeners(EntryListenerManager.java:148)
        at com.hazelcast.client.impl.EntryListenerManager.notifyListeners(EntryListenerManager.java:130)
        at com.hazelcast.client.impl.ListenerManager.customRun(ListenerManager.java:88)
        at com.hazelcast.client.ClientRunnable.run(ClientRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
 [org.apache.solr.common.SolrException:log:161]
metacat-index 20190421-11:50:09: [ERROR]: SolrIndex.update - could not update the solr index for the object urn:uuid:6aa6aa22-00d0-4fe8-93e2-656478dfcdbf since org.apache.solr.client.solrj.SolrServerException: org.apache.solr.common.SolrException: ERROR: [doc=urn:uuid:6aa6aa22-00d0-4fe8-93e2-656478dfcdbf] unknown field 'archived' [edu.ucsb.nceas.metacat.index.SolrIndex:update:604]
```
Looking a bit deeper, I see that the internal call to Solr in `SolrIndex.insertFields()` is failing:
```
metacat-index 20190421-12:54:51: [INFO]: SolrIndex.insertFields - The query to get the original solr doc is ~~~~~~~~~~~~~~~==================q=id%3A%22urn%3Auuid%3Ad4febd9d-b27d-4b13-822d-cbf8d14929f1%22&archived=-archived%3A*fake [edu.ucsb.nceas.metacat.index.SolrIndex:insertFields:460]
```
because the `archived` field is not defined.  So, after diff'ing the ADC's `schema.xml` file with the metacat-common `schema.xml` file, I see that they differ with the `archived`, `replicationStatus`, `replicaVerifiedDate` and `replicationMN` fields (which of course is expected without an automated upgrade).

We need to document these changes in both the Metacat documentation and in the release notes on Github, and provide a step-by-step upgrade process of either replacing or merging the `schema.xml` file with the newest one, and point out that this is necessary for all pre-2.10 installations.  We also need to point out that all old content needs to be reindexed in order to populate these new fields.  This is not trivial for repositories like the KNB and ADC due to their size.

Jing - let's touch base on this - I'm thinking we might be able to reindex content in these repositories in a separate VM, and then swap out the index files on disk.  But nevertheless, let's get this procedure documented since it's a breaking change because no new content shows up in the index (and MetacatUI), and it fails silently from the front-end perspective.

**Comment by taojing2002** [comment]
Hi Chris;

Yes, Metacat will automatically take the care of the schema during the 
upgrade process in the most cases. It will calculate the checksum of the 
file /var/metacat/solr-home/conf/schema.xml and compare that value with 
the list of checksum of all released schema.xml. If the checksum of your 
local schema.xml is found on the list, Metacat will copy the new 
schema.xml to your local server automatically. If Metacat can't find 
your checksum in the list, which means you have modified your local 
schema.xml file, the admin page will show a warning message and ask you 
to merge your local schema.xml with the new schema.xml file on 
/var/lib/tomcat7/webapps/metacat-index/WEB-INF/classes/solr-home/conf/. 
I am just wondering if you saw the message.

Metacat does the same process to handle the upgrade of the 
solrconfig.xml file. Can you compare your local solrconfig.xml with the 
one on 
/var/lib/tomcat7/webapps/metacat-index/WEB-INF/classes/solr-home/conf/solrconfig.xml?

Even though we have a note on the page 
https://knb.ecoinformatics.org/knb/docs/ to ask user to reindex Metacat, 
we should have a message on the admin page as well.

Thanks,
Jing

**Comment by csjx** [comment]
Okay, yeah Jing, I thought that you had planned in the automatic merge. But no, I didn't get any message in the admin pages that a manual merge was needed, so I thought it went through fine.  I also hadn't modified the `schema.xml` that I'm aware of, so we may need to check the logic for the merge.  This was an upgrade from a 2.8.7 Metacat to 2.10.2, so I wonder if that had to do with it?

**Comment by taojing2002** [comment]
Hrrm. I tested couple times from 2.8.2 to 2.10.2 and they worked well. I 
am not sure.
