### ISSUE TITLE
Solr Exception when running unit tests

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacat#1399]
When running `mvn package` from `metacat-index` directory in the `feature-project-indexing` branch the following ERROR occurs intermittently during `OntologyModelServiceTest`:
```
Running edu.ucsb.nceas.metacat.index.annotation.OntologyModelServiceTest
metacat-index 20191023-09:30:14: [ERROR]: org.apache.solr.common.SolrException: Failed to unregister info bean: filterCache
	at org.apache.solr.core.JmxMonitoredMap.unregister(JmxMonitoredMap.java:178)
	at org.apache.solr.core.JmxMonitoredMap.clear(JmxMonitoredMap.java:113)
	at org.apache.solr.core.SolrCore.close(SolrCore.java:707)
	at org.apache.solr.core.CoreContainer.register(CoreContainer.java:416)
	at org.apache.solr.core.CoreContainer.load(CoreContainer.java:333)
	at org.apache.solr.core.CoreContainer.load(CoreContainer.java:216)
	at edu.ucsb.nceas.metacat.common.SolrServerFactory.generateEmbeddedServer(SolrServerFactory.java:90)
	at edu.ucsb.nceas.metacat.common.SolrServerFactory.createSolrServer(SolrServerFactory.java:73)
	at edu.ucsb.nceas.metacat.index.resourcemap.ResourceMapSubprocessor.<clinit>(ResourceMapSubprocessor.java:79)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:990)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:943)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:607)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at edu.ucsb.nceas.metacat.index.ApplicationController.getContext(ApplicationController.java:236)
	at edu.ucsb.nceas.metacat.index.ApplicationController.initialize(ApplicationController.java:206)
	at edu.ucsb.nceas.metacat.index.SolrIndexIT.generateSolrIndex(SolrIndexIT.java:56)
	at edu.ucsb.nceas.metacat.index.annotation.OntologyModelServiceTest.setUp(OntologyModelServiceTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: javax.management.InstanceNotFoundException: solr/:type=filterCache,id=org.apache.solr.search.FastLRUCache
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546)
	at org.apache.solr.core.JmxMonitoredMap.unregister(JmxMonitoredMap.java:172)
	... 59 more
 [org.apache.solr.common.SolrException:log:161]
FOOBAR: edu.ucsb.nceas.metacat.index.annotation.OntologyModelService
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.251 sec
```

**Comment by taojing2002** [comment]
I can't reproduce the issue. It works well to me.

**Comment by gothub** [comment]
Yep, this only occurs for me very infrequently, so kinda hard to track down.
