### ISSUE TITLE
Search Chinese Characters on MetacatUI doesn't work

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1423]
After using the solr external http server 8, I searched some Chinese character and the result panel kept spinning. There was an error message on the catalina.out file:
```
metacat 20200122-15:57:38: [ERROR]: D1ResourceHandler: Serializing exception with code 500: URLDecoder: The query string contains a not-%-escaped byte > 127 at position 22 [edu.ucsb.nceas.metacat.restservice.D1ResourceHandler:serializeException:536]
org.dataone.service.exceptions.ServiceFailure: URLDecoder: The query string contains a not-%-escaped byte > 127 at position 22
	at edu.ucsb.nceas.metacat.dataone.MNodeService.query(MNodeService.java:2037)
	at edu.ucsb.nceas.metacat.restservice.v2.MNResourceHandler.doQuery(MNResourceHandler.java:568)
	at edu.ucsb.nceas.metacat.restservice.v2.MNResourceHandler.handle(MNResourceHandler.java:417)
	at edu.ucsb.nceas.metacat.restservice.D1RestServlet.doGet(D1RestServlet.java:76)
```
I am not sure if this is a new issue or MetacatUI hasn't supported this feature.
@laurenwalker would you shed some light?

**Comment by taojing2002** [comment]
I tried the search with Chinese characters on the `search.dataone.org` and it worked. The version of MetacatUI on `search.dataone.org` is 2.8.4 and I upgraded my local Metacat with this version too. However, the problem still exists. It appears that it is a new issue Metacat introduced.
