### ISSUE TITLE
Reindexing mn-sandbox-ucsb-2 only got about 5000 solr docs even though it has more 50,000 objects

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1424]
We need to investigate  the reason.

**Comment by taojing2002** [comment]
Saw some errors like:
```
MetacatSolrIndex.submit - put the pid MNCallAdapterTierTests.mn-sandbox-ucsb-2.201532773031791.testPackage_dataObj_ into the index queue on hazelcast service successfully. [edu.ucsb.nceas.metacat.index.MetacatSolrIndex:submit:296]
31-Jan-2020 13:26:28.201 WARNING [hz._hzInstance_1_knb.cached.thread-27] com.hazelcast.impl.ConcurrentMapManager.null [127.0.0.1]:5701 [knb] Store thrown exception for CONCURRENT_MAP_GET
 java.lang.RuntimeException
	at edu.ucsb.nceas.metacat.dataone.hazelcast.SystemMetadataMap.load(SystemMetadataMap.java:85)
	at edu.ucsb.nceas.metacat.dataone.hazelcast.SystemMetadataMap.load(SystemMetadataMap.java:25)
	at com.hazelcast.impl.concurrentmap.MapStoreWrapper.load(MapStoreWrapper.java:143)
	at com.hazelcast.impl.ConcurrentMapManager$GetOperationHandler$GetLoader.doMapStoreOperation(ConcurrentMapManager.java:3785)
	at com.hazelcast.impl.ConcurrentMapManager$AbstractMapStoreOperation.run(ConcurrentMapManager.java:3860)
	at com.hazelcast.impl.executor.ParallelExecutorService$ParallelExecutorImpl$ExecutionSegment.run(ParallelExecutorService.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.impl.ExecutorThreadFactory$1.run(ExecutorThreadFactory.java:38)
Caused by: java.lang.NullPointerException
	at java.math.BigInteger.<init>(BigInteger.java:415)
	at java.math.BigInteger.<init>(BigInteger.java:606)
	at edu.ucsb.nceas.metacat.IdentifierManager.getSystemMetadata(IdentifierManager.java:297)
	at edu.ucsb.nceas.metacat.dataone.hazelcast.SystemMetadataMap.load(SystemMetadataMap.java:77)
	... 9 more

metacat-index 20200131-13:26:28: [INFO]: SolrIndex.insetFields - successfully added some extral solr index fields for the objec doi:10.5072/FK2/LTER/knb-lter-gce.144.3 [edu.ucsb.nceas.metacat.index.SolrIndex:insertFields:510]
metacat-index 20200131-13:26:28: [INFO]: ===================================SystemMetadataEventListener. entryUpdated - adding the document doi:10.5072/FK2/LTER/knb-lter-gce.145.3 [edu.ucsb.nceas.metacat.index.SystemMetadataEventListener:entryUpdated:128]
metacat 20200131-13:26:28: [ERROR]: MetacatHandler.buildAllNonResourceMapIndex - can't index the objects since: CONCURRENT_MAP_GET failed at Address[127.0.0.1]:5701 because of an exception thrown at Address[127.0.0.1]:5701 [edu.ucsb.nceas.metacat.MetacatHandler:buildAllNonResourceMapIndex:2848]
```
