### ISSUE TITLE
CSV output for Solr queries fail

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacat#1441]
Jeanette noticed that CSV output is no  longer working in Metacat 2.13.0 installations with external Solr indices:
```
curl "https://knb.ecoinformatics.org/knb/d1/mn/v2/query/solr/?q=*:*&fl=id&wt=csv"
<?xml version="1.0" encoding="UTF-8"?><error detailCode="Solr server error" errorCode="500" name="ServiceFailure">
    <description/>
```
and 
```
curl "https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=*:*&fl=id&wt=csv"
<?xml version="1.0" encoding="UTF-8"?><error detailCode="Solr server error" errorCode="500" name="ServiceFailure">
    <description/>
</error>
```
Note that the exception is coming from the Metacat `SolrQueryResponseTransformer.transformResults()`, which seems to cause an NPE in Solr:
```
java.lang.NullPointerException
	at org.apache.solr.response.TabularResponseWriter.shouldSkipField(TabularResponseWriter.java:100)
	at org.apache.solr.response.CSVWriter.writeResponse(CSVResponseWriter.java:255)
	at org.apache.solr.response.CSVResponseWriter.write(CSVResponseWriter.java:57)
	at edu.ucsb.nceas.metacat.common.query.SolrQueryResponseTransformer.transformResults(SolrQueryResponseTransformer.java:69)
	at edu.ucsb.nceas.metacat.common.query.HttpSolrQueryService.query(HttpSolrQueryService.java:156)
	at edu.ucsb.nceas.metacat.common.query.SolrQueryServiceController.query(SolrQueryServiceController.java:117)
	at edu.ucsb.nceas.metacat.index.MetacatSolrIndex.query(MetacatSolrIndex.java:227)
	at edu.ucsb.nceas.metacat.index.MetacatSolrIndex.query(MetacatSolrIndex.java:187)
	at edu.ucsb.nceas.metacat.index.MetacatSolrIndex.query(MetacatSolrIndex.java:134)
	at edu.ucsb.nceas.metacat.dataone.MNodeService.query(MNodeService.java:2040)
	at edu.ucsb.nceas.metacat.restservice.v2.MNResourceHandler.doQuery(MNResourceHandler.java:572)
	at edu.ucsb.nceas.metacat.restservice.v2.MNResourceHandler.handle(MNResourceHandler.java:421)
	at edu.ucsb.nceas.metacat.restservice.D1RestServlet.doGet(D1RestServlet.java:76)
```
and that direct calls to Solr handle the `wt=csv` parameter fine:
```
curl "http://localhost:8983/solr/metacat-index/select?q=*:*&fl=id&wt=csv"
id
urn:uuid:2adca257-dd16-41bb-8f88-4eb9c172bb21
urn:uuid:6df6239b-dce9-4d1d-99bc-be47d0e97687
urn:uuid:1a4724d2-fcb6-4e65-906d-526c074459dd
urn:uuid:86938691-80e4-4fcb-94ab-28cbbd8e1087
urn:uuid:000a4981-cee6-46de-a0d1-96a9a082e9f6
urn:uuid:c77023e9-860b-4341-b1c3-e7bed7de8d6d
urn:uuid:c6bba1ef-f145-4d53-ac38-89227fc0c9d7
urn:uuid:813e7e18-6637-4c9d-985c-88363641c29a
urn:uuid:7444fed4-9a3d-451f-9e5e-5331660a0009
urn:uuid:1806032d-45ad-4a1c-bc36-494d871a7652
```

**Comment by taojing2002** [comment]
The fix is in the feature-url-access-solr branch and needs more tests.

**Comment by mbjones** [comment]
@taojing2002 I ran into this CSV formatting problem again today. Can you incorporate the fix into the next release please?
