### ISSUE TITLE
Index of the resourcemap failed after publish a package

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1578]
When I tried to publish a package, the index of the resource map failed:
```
[ERROR]: SolrIndex.update - could not update the solr index for the object urn:uuid:8eec771f-16e5-4d7b-b759-ea6443cbedd4 since FWK005 parse may not be called while parsing. [edu.ucsb.nceas.metacat.index.SolrIndex:update:626]
org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[xercesImpl-2.9.1.jar:?]
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[xercesImpl-2.9.1.jar:?]
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) ~[?:1.8.0_311]
	at edu.ucsb.nceas.metacat.index.SolrIndex.generateXmlDocument(SolrIndex.java:362) ~[classes/:?]
	at edu.ucsb.nceas.metacat.index.SolrIndex.process(SolrIndex.java:204) ~[classes/:?]
	at edu.ucsb.nceas.metacat.index.SolrIndex.insert(SolrIndex.java:429) ~[classes/:?]
	at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:667) ~[classes/:?]
	at edu.ucsb.nceas.metacat.index.SolrIndex.update(SolrIndex.java:614) [classes/:?]
	at edu.ucsb.nceas.metacat.index.SystemMetadataEventListener$1.run(SystemMetadataEventListener.java:171) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_311]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_311]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]

```

**Comment by taojing2002** [comment]
This error happened when multiple threads try to access a xml DocumentBuilder object. I switched to the subprocessor of the system metadata one ( we used a customized one), the error is gone.
