### ISSUE TITLE
Support Solr 9.5.0

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1822]
* Test current code with solr 9 and determine upgrade path for 3.0.0 release
    * Solr 9.5 does not work, but solr 9.0 does!?
* Metacat solr library is still at v8 - need to upgrade to 9, but not easy

**Comment by taojing2002** [comment]
The latest Solr version which our solr admin page can work with is `9.1.1`.

Solr `9.5`, `9.4`, `9.3` and `9.2` doesn't work well with it.

**Comment by taojing2002** [comment]
It seems our `solrconfig.xml` has an issue when it runs against solr `9.5`:
```
Caused by: org.apache.solr.common.SolrException: Error loading solr config from /var/metacat/solr-home3/conf/solrconfig.xml
	at org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:161) ~[?:?]
	at org.apache.solr.core.ConfigSetService.createSolrConfig(ConfigSetService.java:309) ~[?:?]
	at org.apache.solr.core.ConfigSetService.loadConfigSet(ConfigSetService.java:262) ~[?:?]
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1707) ~[?:?]
	at org.apache.solr.core.CoreContainer.lambda$loadInternal$12(CoreContainer.java:1057) ~[?:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:212) ~[metrics-core-4.2.21.jar:4.2.21]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:299) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.lang.RuntimeException: [solrconfig.xml] circuitBreaker: missing mandatory attribute 'class'
```

**Comment by taojing2002** [comment]
In solr 9.5, it doesn't like the wild card `*` setting in `solr.bin.sh`:
```
SOLR_OPTS="$SOLR_OPTS -Dsolr.allowPaths=*"
```
You should specify the exact path. Also it should NOT be a link path, it should be the real path:
```
SOLR_OPTS="$SOLR_OPTS -Dsolr.allowPaths=/private/var/metacat"
```
