### ISSUE TITLE
OstiDOIServiceIT failed

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1859]
I ran this test class and it failed.
```
Testcase: testPublishIdentifierPrivatePackageToPublic took 85.143 sec
  Caused an ERROR                                                                                                           
Illegal URI: https//:foo.dataone.org/v1/resolve/testPublishPrivatePackageToPublic-resourcemap.1712034621436#aggregation; Aggregation requires a protocol-based URI
org.dspace.foresite.OREException: Illegal URI: https//:foo.dataone.org/v1/resolve/testPublishPrivatePackageToPublic-resourcemap.1712034621436#aggregation; Aggregation requires a protocol-based URI
  at org.dspace.foresite.jena.AggregationJena.initialise(AggregationJena.java:117)
  at org.dspace.foresite.OREFactory.createAggregation(OREFactory.java:78)
  at org.dataone.ore.ResourceMapFactory.createResourceMap(ResourceMapFactory.java:168)
  at org.dataone.ore.ResourceMapFactory.createResourceMap(ResourceMapFactory.java:206)
  at edu.ucsb.nceas.metacat.doi.osti.OstiDOIServiceIT.testPublishIdentifierPrivatePackageToPublic(OstiDOIServiceIT.java:559)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
```
Testcase: testPublishIdentifierPrivatePackageToPartialPublic took 85.284 sec
  Caused an ERROR
Illegal URI: https//:foo.dataone.org/v1/resolve/testPublishIdentifierPrivatePackageToPartialPublic-resourcemap.1712034706790#aggregation; Aggregation requires a protocol-based URI
org.dspace.foresite.OREException: Illegal URI: https//:foo.dataone.org/v1/resolve/testPublishIdentifierPrivatePackageToPartialPublic-resourcemap.1712034706790#aggregation; Aggregation requires a protocol-based URI
  at org.dspace.foresite.jena.AggregationJena.initialise(AggregationJena.java:117)
  at org.dspace.foresite.OREFactory.createAggregation(OREFactory.java:78)
  at org.dataone.ore.ResourceMapFactory.createResourceMap(ResourceMapFactory.java:168)
  at org.dataone.ore.ResourceMapFactory.createResourceMap(ResourceMapFactory.java:206)
  at edu.ucsb.nceas.metacat.doi.osti.OstiDOIServiceIT.testPublishIdentifierPrivatePackageToPartialPublic(OstiDOIServiceIT.java:744)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by mbjones** [comment]
@taojing2002 could you please summarize the problem and your fix so people can understand at a high level why this issue was closed? Thank you.

**Comment by taojing2002** [comment]
This issue was caused by this class using a wrong cn url in the resource map files. After we changed the class to junit 4 and it uses the production cn url to for the resource map files, the error is gone.
