### ISSUE TITLE
Move GOA to K8s

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1996]
Tracking progress for moving `goa.nceas.ucsb.edu` to k8s prod cluster.

Add any notes to this issue, and follow checklist in sub-issue #2061

**Comment by artntek** [comment]
Initial rsync

```shell
brkoke@mn-ucsb-2:~/.ssh$ time rsync -aHAX /var/goa/ brooke@arctica.nceas.ucsb.edu:/mnt/pdg/repos/goa/metacat/
rsync: [generator] chgrp "/mnt/pdg/repos/goa/metacat/." failed: Operation not permitted (1)
rsync: [sender] send_files failed to open "/var/goa/certs/urn_node_GOA-2.pem": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/certs/urn_node_GOA-3.zip": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/data/autogen.2023102513341600200.1": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/data/autogen.2023102513341984501.1": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/data/autogen.2023102513342157402.1": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/data/autogen.2023102513401192703.1": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/data/autogen.2023102513435709004.1": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/documents/df35b.19.7": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2019-22": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2019-23": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2019-25": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2019-29": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2019-35": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2019-42": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2019-46": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2019-48": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2019-51": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2020-03": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2020-06": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2020-07": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2020-13": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2020-22": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/logs/metacatreplication.log.2020-27": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/solr-last-proccessed-date": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_enyl.fdt": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_enyl.fdx": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_enyl.fnm": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_enyl.frq": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_enyl.nrm": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_enyl.prx": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_enyl.tii": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_enyl.tis": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_enyl_dp.del": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fua2.fdt": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fua2.fdx": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fua2.fnm": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fua2.frq": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fua2.nrm": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fua2.prx": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fua2.tii": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fua2.tis": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fua2_1t.del": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fusn.fdt": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fusn.fdx": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fusn.fnm": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fusn.frq": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fusn.nrm": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fusn.prx": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fusn.tii": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fusn.tis": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fusn_1.del": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fuso.fdt": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fuso.fdx": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fuso.fnm": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fuso.frq": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fuso.nrm": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fuso.prx": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fuso.tii": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/_fuso.tis": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/segments.gen": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home-old/data/index/segments_gzi1": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/solr-home2/solr-last-proccessed-date": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002946.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002947.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002948.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002949.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002950.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002951.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002952.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002953.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002954.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002955.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002956.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002957.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002958.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002959.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002960.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002961.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002962.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002963.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002964.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002965.tmp": Permission denied (13)
rsync: [sender] send_files failed to open "/var/goa/temporary/upload__7991a9df_16ea4edd1f0__8000_00002966.tmp": Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]

real	5m18.979s
user	1m34.476s
sys	1m36.592s
brooke@mn-ucsb-2:~/.ssh$
```

**Comment by artntek** [comment]
Next action: GOA k8s initial setup (values overrides, PVs, secrets, metacatui theme etc)

**Comment by artntek** [comment]
ok - all finished and hashstore conversion errors taken care of. Changed values (external URL etc) to reflect live goa site, and pointed metacat at the prod CN,,, but at this point I could not get it to start up due to the following error:

```java
metacat 20250213-23:38:41: [INFO]: nodeIdMatchesClientCert(): TRUE! (nodeId: urn:node:GOA; Common Name (CN) from client cert: urn:node:GOA [edu.ucsb.nceas.metacat.admin.D1AdminCNUpdater:nodeIdMatchesClientCert:268]
metacat 20250213-23:38:41: [INFO]: Sending updated node capabilities to DataONE CN: https://cn.dataone.org/cn/v2 [edu.ucsb.nceas.metacat.admin.D1AdminCNUpdater:updateCN:403]
metacat 20250213-23:38:41: [INFO]: temp outputFile is: /usr/local/tomcat/temp/mmp.output.6491576582861615276.tmp [org.dataone.mimemultipart.SimpleMultipartEntity:generateTempFile:211]
[...]
metacat 20250213-23:38:42: [DEBUG]: Starting handshake [org.apache.http.conn.ssl.SSLConnectionSocketFactory:createLayeredSocket:435]
metacat 20250213-23:38:42: [DEBUG]: Secure session established [org.apache.http.conn.ssl.SSLConnectionSocketFactory:verifyHostname:465]
metacat 20250213-23:38:42: [DEBUG]:  negotiated protocol: TLSv1.2 [org.apache.http.conn.ssl.SSLConnectionSocketFactory:verifyHostname:466]
metacat 20250213-23:38:42: [DEBUG]:  negotiated cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 [org.apache.http.conn.ssl.SSLConnectionSocketFactory:verifyHostname:467]
metacat 20250213-23:38:42: [DEBUG]:  peer principal: CN=cn.dataone.org [org.apache.http.conn.ssl.SSLConnectionSocketFactory:verifyHostname:475]
metacat 20250213-23:38:42: [DEBUG]:  peer alternative names: [cn-orc-1.dataone.org, cn-secondary.dataone.org, cn-ucsb-1.dataone.org, cn.dataone.org] [org.apache.http.conn.ssl.SSLConnectionSocketFactory:verifyHostname:484]
metacat 20250213-23:38:42: [DEBUG]:  issuer principal: CN=R10, O=Let's Encrypt, C=US [org.apache.http.conn.ssl.SSLConnectionSocketFactory:verifyHostname:488]
metacat 20250213-23:38:42: [DEBUG]: Connection established 192.168.197.198:45274<->128.111.85.180:443 [org.apache.http.impl.conn.DefaultHttpClientConnectionOperator:connect:146]
metacat 20250213-23:38:42: [DEBUG]: http-outgoing-2: set socket timeout to 30000 [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:setSocketTimeout:88]
metacat 20250213-23:38:42: [DEBUG]: Executing request PUT /cn/v2/node/urn:node:GOA HTTP/1.1 [org.apache.http.impl.execchain.MainClientExec:execute:255]
metacat 20250213-23:38:42: [DEBUG]: Target auth state: UNCHALLENGED [org.apache.http.impl.execchain.MainClientExec:execute:260]
metacat 20250213-23:38:42: [DEBUG]: Proxy auth state: UNCHALLENGED [org.apache.http.impl.execchain.MainClientExec:execute:266]
metacat 20250213-23:38:42: [DEBUG]: http-outgoing-2 >> PUT /cn/v2/node/urn:node:GOA HTTP/1.1 [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:onRequestSubmitted:133]
metacat 20250213-23:38:42: [DEBUG]: http-outgoing-2 >> Content-Length: 2882 [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:onRequestSubmitted:136]
metacat 20250213-23:38:42: [DEBUG]: http-outgoing-2 >> Content-Type: multipart/form-data; boundary=ATO-ok0tCzQ3O1jM4FOQRGXxvFwGbiZ5wh2SbP; charset=US-ASCII [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:onRequestSubmitted:136]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> Host: cn.dataone.org [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:onRequestSubmitted:136]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> Connection: Keep-Alive [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:onRequestSubmitted:136]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> User-Agent: Apache-HttpClient/4.5.13 (Java/17.0.13) [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:onRequestSubmitted:136]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> Accept-Encoding: gzip,deflate [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:onRequestSubmitted:136]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> Via: 1.1 localhost (Apache-HttpClient/4.5.13 (cache)) [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:onRequestSubmitted:136]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> "PUT /cn/v2/node/urn:node:GOA HTTP/1.1[\r][\n]" [org.apache.http.impl.conn.Wire:wire:73]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> "Content-Length: 2881[\r][\n]" [org.apache.http.impl.conn.Wire:wire:73]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> "Content-Type: multipart/form-data; boundary=P-2RPzJHT3IpmFRQvMc2TkBHV89dhCJkk0RaL; charset=US-ASCII[\r][\n]" [org.apache.http.impl.conn.Wire:wire:73
[...]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> "</ns3:node>[\n]" [org.apache.http.impl.conn.Wire:wire:73]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> "[\r][\n]" [org.apache.http.impl.conn.Wire:wire:73]
metacat 20250213-23:34:45: [DEBUG]: http-outgoing-2 >> "--P-2RPzJHT3IpmFRQvMc2TkBHV89dhCJkk0RaL--[\r][\n]" [org.apache.http.impl.conn.Wire:wire:73]
metacat 20250213-23:34:53: [DEBUG]: Connection [id:1][route:{s}->https://cn.dataone.org:443][state:CN=urn:node:GOA, DC=dataone, DC=org] expired @ Thu Feb 13 23:34:50 UTC 2025 [org.apache.http.impl.conn.CPoolEntry:isExpired:82]
metacat 20250213-23:34:53: [DEBUG]: http-outgoing-1: Close connection [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:close:79]
metacat 20250213-23:34:53: [DEBUG]: Connection [id:0][route:{s}->https://cn.dataone.org:443][state:CN=urn:node:GOA, DC=dataone, DC=org] expired @ Thu Feb 13 23:34:49 UTC 2025 [org.apache.http.impl.conn.CPoolEntry:isExpired:82]
metacat 20250213-23:34:53: [DEBUG]: http-outgoing-0: Close connection [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:close:79]
metacat 20250213-23:35:15: [DEBUG]: http-outgoing-2 << "[read] I/O error: Read timed out" [org.apache.http.impl.conn.Wire:wire:87]
metacat 20250213-23:35:15: [DEBUG]: http-outgoing-2: Close connection [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:close:79]
metacat 20250213-23:35:15: [DEBUG]: http-outgoing-2: Shutdown connection [org.apache.http.impl.conn.LoggingManagedHttpClientConnection:shutdown:96]
metacat 20250213-23:35:15: [DEBUG]: Connection discarded [org.apache.http.impl.execchain.ConnectionHolder:abortConnection:129]
metacat 20250213-23:35:15: [ERROR]: Calling CNode.updateNodeCapabilities() with CN URL: https://cn.dataone.org/cn/v2, and nodeId: urn:node:GOA; error message was: class org.dataone.client.exception.ClientSideException: /Read timed out [edu.ucsb.nceas.metacat.admin.D1AdminCNUpdater:updateCN:411]
org.dataone.service.exceptions.ServiceFailure: class org.dataone.client.exception.ClientSideException: /Read timed out
	at org.dataone.client.rest.HttpMultipartRestClient.doPutRequest(HttpMultipartRestClient.java:448) ~[d1_libclient_java-2.3.1.jar:?]
	at org.dataone.client.v2.impl.MultipartCNode.updateNodeCapabilities(MultipartCNode.java:1585) ~[d1_libclient_java-2.3.1.jar:?]
	at edu.ucsb.nceas.metacat.admin.D1AdminCNUpdater.updateCN(D1AdminCNUpdater.java:406) [metacat.jar:?]
	at edu.ucsb.nceas.metacat.admin.D1AdminCNUpdater.configPreregisteredMN(D1AdminCNUpdater.java:182) [metacat.jar:?]
	at edu.ucsb.nceas.metacat.admin.D1Admin.upRegD1MemberNode(D1Admin.java:433) [metacat.jar:?]
	at edu.ucsb.nceas.metacat.startup.K8sAdminInitializer.initK8sD1Admin(K8sAdminInitializer.java:127) [metacat.jar:?]
	at edu.ucsb.nceas.metacat.startup.K8sAdminInitializer.initializeK8sInstance(K8sAdminInitializer.java:53) [metacat.jar:?]
	at edu.ucsb.nceas.metacat.startup.MetacatInitializer.initAfterMetacatConfig(MetacatInitializer.java:162) [metacat.jar:?]
	at edu.ucsb.nceas.metacat.startup.MetacatInitializer.contextInitialized(MetacatInitializer.java:103) [metacat.jar:?]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4005) [catalina.jar:9.0.96]
[...]
Caused by: org.dataone.client.exception.ClientSideException: /Read timed out
	... 50 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at sun.nio.ch.NioSocketImpl.timedRead(Unknown Source) ~[?:?]
[...]
metacat 20250213-23:39:12: [ERROR]: configPreregisteredMN: *** FAILED *** to push an update of Member Node settings to the CN (nodeId unchanged) [edu.ucsb.nceas.metacat.admin.D1AdminCNUpdater:configPreregisteredMN:187]
metacat 20250213-23:39:12: [ERROR]: initializeContainerizedD1Admin(): error calling D1Admin.getInstance().upRegD1MemberNode: configPreregisteredMN: *** FAILED *** to push an update of Member Node settings to the CN (nodeId unchanged) [edu.ucsb.nceas.metacat.startup.K8sAdminInitializer:initK8sD1Admin:131]
edu.ucsb.nceas.metacat.admin.AdminException: configPreregisteredMN: *** FAILED *** to push an update of Member Node settings to the CN (nodeId unchanged)
	at edu.ucsb.nceas.metacat.admin.D1AdminCNUpdater.configPreregisteredMN(D1AdminCNUpdater.java:188) ~[metacat.jar:?]
	at edu.ucsb.nceas.metacat.admin.D1Admin.upRegD1MemberNode(D1Admin.java:433) ~[metacat.jar:?]
	at edu.ucsb.nceas.metacat.startup.K8sAdminInitializer.initK8sD1Admin(K8sAdminInitializer.java:127) [metacat.jar:?]
[...]
```

This implies that the attempted `PUT` to `https://cn.dataone.org/cn/v2/node/urn:node:GOA` manages to complete the connection/SSL handshake, but then seems to time out waiting for the response to the `PUT`

**Comment by artntek** [comment]
I am able to curl (GET) the cn from a container in the same namespace as the metacat pod:

```shell
root@busybox-netutils:/# curl https://cn.dataone.org/cn/v2/node/urn:node:GOA

<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl"
  href="/cn/xslt/dataone.types.v2.xsl" ?>
<ns3:node xmlns:ns2="http://ns.dataone.org/service/types/v1"
  xmlns:ns3="http://ns.dataone.org/service/types/v2.0" replicate="false" synchronize="true"
  type="mn" state="up">
    <identifier>urn:node:GOA</identifier>
    <name>Gulf of Alaska Data Portal</name>
[...etc]
```

**Comment by taojing2002** [comment]
May you try to update the node document by the curl command like this:

curl --cert your-node-certificate -X PUT -F ***@***.***' "
https://cn-stage.test.dataone.org/cn/v2/node"

**Comment by artntek** [comment]
> May you try to update the node document by the curl command like this:
> 
> curl --cert your-node-certificate -X PUT -F ***@***.***' "
> https://cn-stage.test.dataone.org/cn/v2/node"

Not sure about this - let's discuss in person:
- the form clause is incorrectly formatted: `PUT -F ***@***.***'`. I think curl is looking for key=value pairs? Assuming it should be `contactSubject=`...
  
- I tried with the GOA cert, but I got a CA error, because `cn-stage.test.dataone.org` uses the test CA.
  ```shell
  tomcat@metacatgoa-0:~$ curl --cert _DELETEME_GOA_node.crt  -X PUT -F 'contactSubject=***@***.***' "https://cn-stage.test.dataone.org/cn/v2/node"
  curl: (56) OpenSSL SSL_read: error:0A000418:SSL routines::tlsv1 alert unknown ca, errno 0
  ```

- I tried with the test.arcticdata.io node cert, which uses the test CA, but got another error:
  ```shell
  tomcat@metacatgoa-0:~$ curl --cert _DELETEME_TESTARCTIC_node.crt  -X PUT -F 'contactSubject=XXXX@XXXX.XXX' "https://cn-stage.test.dataone.org/cn/v2/node"
  <?xml version="1.0" encoding="UTF-8"?>
  <error detailCode="500" errorCode="500" name="ServiceFailure">
    <description>Internal Server Error: The server encountered an unexpected condition which
                 prevented it from fulfilling the request.</description>
  </error>
  ```

(...and in reading the CN API docs, it appears I was liucky it failed, because if you update just one field like this, it would overwrite all the other non-specified fields and make them empty 😅)

**Comment by artntek** [comment]
## SOLVED

Jing's a genius, yet again...

We tried two `curl` updates from my laptop to the prod CN:
1. using the ESA node cert to update ESA node details. Took 2 seconds
2. using the GOA node cert to update GOA node details. Took around 55 seconds

example:
```shell
time curl --cert GOA.pem -X PUT -F 'node=@node.xml' "https://cn.test.dataone.org/cn/v2/node"

# where ./node.xml contains the xml doc from https://goa.nceas.ucsb.edu/goa/d1/mn/v2/node
```

My hypothesis is that the metacat/dataone code timeout is shorter than this, which is why it's failing.

The explanation?
```xml
<contactSubject>CN=Matt Jones A729,O=Google,C=US,DC=cilogon,DC=org</contactSubject>
```

The CN took a l-o-n-g time to do a lookup of all Matt's details, probably because he is a member of so many groups etc(??). Anyway, it generates a ton of log errors etc, and takes a long time. Once we replaced this with Chris' details instead, the PUT took 2 seconds, just like ESA...

**Comment by artntek** [comment]
All up and working, but currently based on an unreleased version of the helm chart in the `develop` branch ([see changelog](https://github.nceas.ucsb.edu/NCEAS/k8s-cluster-config/blob/main/prod_cluster/metacatgoa/CHANGELOG.md)). 

Need to redeploy with the official version after it is released
