### ISSUE TITLE
KNB Data Catalog Map does not display points

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#407]
---

Author Name: **Callie Bowdish** (Callie Bowdish)
Original Redmine Issue: 2716, https://projects.ecoinformatics.org/ecoinfo/issues/2716
Original Date: 2007-01-08
Original Assignee: Jing Tao

---

Metacat data bounds is not working working for the KNB Data Catalog Map. http://knb.ecoinformatics.org/index_map.jsp displays the map with no points representing the datasets. The option box Dataset Bounds text is crossed out.

Here is the errors in the server log that jing saw:
org.vfny.geoserver.wms.WmsException: java.util.NoSuchElementException: Could not locate FeatureTypeConfig 'metacat:data_bounds'
at org.vfny.geoserver.wms.requests.GetMapKvpReader.findLayer(GetMapKvpReader.java:1215)
at org.vfny.geoserver.wms.requests.GetMapKvpReader.parseLayersParam(GetMapKvpReader.java:1190)
at org.vfny.geoserver.wms.requests.GetMapKvpReader.parseLayersAndStyles(GetMapKvpReader.java:688)
at org.vfny.geoserver.wms.requests.GetMapKvpReader.parseMandatoryParameters(GetMapKvpReader.java:389)
at org.vfny.geoserver.wms.requests.GetMapKvpReader.getRequest(GetMapKvpReader.java:226)
at org.vfny.geoserver.servlets.AbstractService.doGet(AbstractService.java:318)

jing and some error about the file couldn't find:
/var/www/org.ecoinformatics.knb1/knb/data/metacat_shps/data_points.shp

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Jing Tao** (Jing Tao)
Original Date: 2007-01-17T22:38:47Z

---

After changing regenerateSpacialCache's value to true in metacat.properties, the tomcat restarted. It took about 30 minutes to regenerate the cache. The knb site now is working.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Callie Bowdish** (Callie Bowdish)
Original Date: 2007-01-26T00:01:19Z

---

The KNB Data Catalog Map has had the Dataset Points be unavailable three different times. After each one it requires a reboot to get it to work again. Jing mentioned that the the spatial cache is kind of corrupted. Because of the way this is set up we have a blank spot on the front page where it says "View Interactive Map".

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Jing Tao** (Jing Tao)
Original Date: 2007-02-26T23:57:59Z

---

According to my search and conversation with Matt Perry, the problem is we use shape file to store the geo information which is not recommended in a production
server.

I tried to insert and delete 400 eml docs to the test server from 4 machines simultaneously. However, i can't duplicate the problem.

In KNB machine, the problem happened once a week in avarage

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Matt Jones** (Matt Jones)
Original Date: 2007-03-22T17:31:33Z

---

Fixed by synchronizing for multithreaded access to the shapefile.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:21:05Z

---

Original Bugzilla ID was 2716
