### ISSUE TITLE
another permissions error when registering dataset in nceas skin

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#614]
---

Author Name: **Michael Daigle** (Michael Daigle)
Original Redmine Issue: 3763, https://projects.ecoinformatics.org/ecoinfo/issues/3763
Original Date: 2009-01-21
Original Assignee: Michael Daigle

---

When registering a dataset with a data file, Metacat is throwing the following exception:

MC 14:29:17,633: [ERROR]: Problem with parsing: General error checking user permissions: User tried to update an access module when they don't have "ALL" permission! [edu.ucsb.nceas.metacat.DocumentImpl]
org.xml.sax.SAXException: General error checking user permissions: User tried to update an access module when they don't have "ALL" permission!
	at edu.ucsb.nceas.metacat.Eml210SAXHandler.writeAdditionalAccessRulesToDB(Eml210SAXHandler.java:1576)
	at edu.ucsb.nceas.metacat.Eml210SAXHandler.writeAccessRuleToDB(Eml210SAXHandler.java:1382)
	at edu.ucsb.nceas.metacat.Eml210SAXHandler.endDocument(Eml210SAXHandler.java:1363)
	at org.apache.xerces.parsers.AbstractSAXParser.endDocument(Unknown Source)
 . . .

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Michael Daigle** (Michael Daigle)
Original Date: 2009-01-22T00:30:48Z

---

Metacat was checking for xml_access when uploading a new data file.  Changed so that it only checks for existing data files.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:24:28Z

---

Original Bugzilla ID was 3763
