### ISSUE TITLE
Null sessionids causing configuration to fail

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#622]
---

Author Name: **Michael Daigle** (Michael Daigle)
Original Redmine Issue: 3778, https://projects.ecoinformatics.org/ecoinfo/issues/3778
Original Date: 2009-01-26
Original Assignee: Michael Daigle

---

null session Id's are causing metacat to throw null pointer exceptions

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Michael Daigle** (Michael Daigle)
Original Date: 2009-01-26T23:07:03Z

---

   1.
      Jan 26, 2009 2:15:48 PM org.apache.catalina.core.StandardWrapperValve invoke
   2.
      SEVERE: Servlet.service() for servlet MetaCatAdmin threw exception
   3.
      java.lang.NullPointerException
   4.
              at edu.ucsb.nceas.metacat.service.SessionService.isSessionRegistered(SessionService.java:120)
   5.
              at edu.ucsb.nceas.metacat.service.SessionService.touchSession(SessionService.java:148)
   6.
              at edu.ucsb.nceas.metacat.admin.MetaCatAdminServlet.handleGetOrPost(MetaCatAdminServlet.java:103)
   7.
              at edu.ucsb.nceas.metacat.admin.MetaCatAdminServlet.doPost(MetaCatAdminServlet.java:81)
   8.
              at javax.servlet.http.HttpServlet.service(HttpServlet.java:709)
   9.
              at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
  10.
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
  11.
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
  12.
              at org.vfny.geoserver.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)
  13.
              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
  14.
              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
  15.
              at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
  16.
              at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:172)
  17.
              at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:433)
  18.
              at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
  19.
              at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
  20.
              at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
  21.
              at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:151)
  22.
              at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:200)
  23.
              at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:283)
  24.
              at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:773)
  25.
              at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:703)
  26.
              at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:895)
  27.
              at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)
  28.
              at java.lang.Thread.run(Thread.java:595)

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Michael Daigle** (Michael Daigle)
Original Date: 2009-01-27T00:49:00Z

---

This turned out to be a byproduct of a bad skin configuration.  I went ahead and added checks for null session ids so the exceptions could be handled gracefully as opposed to throwing a NPE.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:24:31Z

---

Original Bugzilla ID was 3778
