### ISSUE TITLE
"DatabaseService is already registered" error after configuring Metacat

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#744]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 4886, https://projects.ecoinformatics.org/ecoinfo/issues/4886
Original Date: 2010-03-17
Original Assignee: ben leinfelder

---

I installed Metacat from 1.9.2 branch and configured it successfully. Then I typed
the url on the browser:
http://chico1.dyndns.org/knb/metacat?action=read&qformat=knb&docid=tao.14547

I got the error:
javax.servlet.ServletException: Service problem while intializing MetaCat Servlet: ServiceService.registerService - Service: DatabaseService is already registered. Use ServiceService.reregister() to replace the service.
	edu.ucsb.nceas.metacat.MetaCatServlet.initSecondHalf(MetaCatServlet.java:490)
	edu.ucsb.nceas.metacat.MetaCatServlet.handleGetOrPost(MetaCatServlet.java:696)
	edu.ucsb.nceas.metacat.MetaCatServlet.doGet(MetaCatServlet.java:519)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
	org.vfny.geoserver.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)

I had to restart tomcat and error was gone.

Paul Were sent an email to metacat-dev describing that he got the same error:

I installed metacat 192RC4 and configured it ok.

I am now attempting run the registry.

I get the Registry login page but whenever I try to log in it fails. I get the following error.

knb 20100316-11:49:55: [ERROR]: MetaCatServlet.initSecondHalf - Service problem while initializing MetaCat Servlet: ServiceService.registerService - Service:
DatabaseService is already registered. Use ServiceService.reregister() to replace the service. [edu.ucsb.nceas.metacat.MetaCatServlet]

I am able to login into the admin page with no error as

uid=pwere,o=unaffiliated,dc=ecoinformatics,dc=org

and that is the same login I am using for the registry.

Jing's comment: i guess the "registry" in Paul's email means metacat.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Duane Costa** (Duane Costa)
Original Date: 2010-11-10T02:22:59Z

---

We are now seeing this same behavior at LTER upon upgrading to Metacat 1.9.3. Prior to the 1.9.3 upgrade, we had never had this error occur before. As reported by Jing and Paul in the original bug report, the error mysteriously goes away with a restart of Tomcat/Metacat.

2010-11-09 18:54:57.732 Metacat: [ERROR] [edu.ucsb.nceas.metacat.MetaCatServlet]: MetaCatServlet.initSecondHalf - Service problem while intializing MetaCat Servlet: ServiceService.registerService - Service: DatabaseService is already registered. Use ServiceService.reregister() to replace the service. 
edu.ucsb.nceas.metacat.shared.ServiceException: ServiceService.registerService - Service: DatabaseService is already registered. Use ServiceService.reregister() to replace the service.
        at edu.ucsb.nceas.metacat.service.ServiceService.registerService(ServiceService.java:91)
        at edu.ucsb.nceas.metacat.MetaCatServlet.initSecondHalf(MetaCatServlet.java:375)
        at edu.ucsb.nceas.metacat.MetaCatServlet.handleGetOrPost(MetaCatServlet.java:705)
        at edu.ucsb.nceas.metacat.MetaCatServlet.doGet(MetaCatServlet.java:526)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.vfny.geoserver.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:433)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:845)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
        at java.lang.Thread.run(Thread.java:619)

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:28:27Z

---

Original Bugzilla ID was 4886

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2013-04-03T22:07:24Z

---

We still get this from time to time. Sometimes it even takes a few restarts of tomcat to get it running again.
