### ISSUE TITLE
EcogridWriter doesn't work with the metacat built from trunk.

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#769]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 5353, https://projects.ecoinformatics.org/ecoinfo/issues/5353
Original Date: 2011-03-21
Original Assignee: Chris Jones

---

When I used EcogridWriter to write metadata and data into dev.nceas' metadata, it worked file. I believe the version of the metadata is 1.9.3

I built my local metacat by revision 6013 from the svn trunk.
But when i used EcogridWriter to write metadata and data file into it, it gave me the following error:

EML document type: eml://ecoinformatics.org/eml-2.0.0
edu.ucsb.nceas.metacat.McdbDocNotFoundException: 2Could not find document doc.130074542695043
	at edu.ucsb.nceas.metacat.IdentifierManager.getDocumentInfo(IdentifierManager.java:246)
	at edu.ucsb.nceas.metacat.MetacatHandler.createSystemMetadata(MetacatHandler.java:3477)
	at edu.ucsb.nceas.metacat.MetacatHandler.createSystemMetadata(MetacatHandler.java:3618)
	at edu.ucsb.nceas.metacat.MetacatHandler.handleInsertOrUpdateAction(MetacatHandler.java:1862)
	at edu.ucsb.nceas.metacat.MetaCatServlet.handleGetOrPost(MetaCatServlet.java:885)
	at edu.ucsb.nceas.metacat.MetaCatServlet.doPost(MetaCatServlet.java:493)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Thread.java:619)

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Matt Jones** (Matt Jones)
Original Date: 2011-03-21T22:55:46Z

---

Probably due to EcoGrid entry path not being the same as others, and so parameters missing in DataONE system metadata calls.  Chris and Chad created these functions, so I am assigning to Chris to debug.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2011-11-09T20:14:49Z

---

Is there a sample Kepler workflow we can use to debug this?

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2011-11-09T22:56:23Z

---

I tried this out with Kepler 2.1, writing sample EML 2.0.0 and EML 2.1.0 metadata (and data files). All worked out fine for me.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2011-11-09T23:19:49Z

---

Both Jing and I were unable to replicate this bug testing against a more recent Metacat trunk build

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:30:08Z

---

Original Bugzilla ID was 5353
