### ISSUE TITLE
Got an NPE when upgrade db from 1.9.5 to 2.0.0

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#809]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 5562, https://projects.ecoinformatics.org/ecoinfo/issues/5562
Original Date: 2011-12-02
Original Assignee: ben leinfelder

---

knb 20111202-11:20:14: [ERROR]: SkinsAdmin.configureSkins - Could not find properties for skin: semtools [edu.ucsb.nceas.metacat.admin.SkinsAdmin]
knb 20111202-11:20:22: [ERROR]: SkinsAdmin.configureSkins - Could not find metadata for skin: semtools [edu.ucsb.nceas.metacat.admin.SkinsAdmin]
knb 20111202-11:20:35: [ERROR]: Error updating date time node data: null [edu.ucsb.nceas.metacat.admin.upgrade.UpgradeNodeDataDatetime]
java.lang.NullPointerException
	at edu.ucsb.nceas.metacat.admin.upgrade.UpgradeNodeDataDatetime.upgradeSingleTable(UpgradeNodeDataDatetime.java:129)
	at edu.ucsb.nceas.metacat.admin.upgrade.UpgradeNodeDataDatetime.upgrade(UpgradeNodeDataDatetime.java:61)
	at edu.ucsb.nceas.metacat.admin.upgrade.Upgrade2_0_0.upgrade(Upgrade2_0_0.java:40)
	at edu.ucsb.nceas.metacat.admin.DBAdmin.upgradeDatabase(DBAdmin.java:804)
	at edu.ucsb.nceas.metacat.admin.DBAdmin.configureDatabase(DBAdmin.java:208)
	at edu.ucsb.nceas.metacat.admin.MetacatAdminServlet.handleGetOrPost(MetacatAdminServlet.java:167)
	at edu.ucsb.nceas.metacat.admin.MetacatAdminServlet.doGet(MetacatAdminServlet.java:74)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Thread.java:619)

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2011-12-02T19:28:48Z

---

it was possible to have a null prepared statement if there were no data values to convert to dates -- now checking for that

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:30:54Z

---

Original Bugzilla ID was 5562
