### ISSUE TITLE
Get an exception during startup metacat

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#813]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 5568, https://projects.ecoinformatics.org/ecoinfo/issues/5568
Original Date: 2011-12-20
Original Assignee: ben leinfelder

---

I got an exception when i started metacat. However, it seems that metacat still can work.

SEVERE: /127.0.0.1:5701 [DataONE] null
java.lang.RuntimeException
	at edu.ucsb.nceas.metacat.dataone.hazelcast.SystemMetadataMap.load(SystemMetadataMap.java:70)
	at edu.ucsb.nceas.metacat.dataone.hazelcast.SystemMetadataMap.loadAll(SystemMetadataMap.java:79)
	at com.hazelcast.impl.concurrentmap.MapStoreWrapper.loadAll(MapStoreWrapper.java:148)
	at com.hazelcast.impl.FactoryImpl.loadKeys(FactoryImpl.java:586)
	at com.hazelcast.impl.FactoryImpl.checkInitialization(FactoryImpl.java:568)
	at com.hazelcast.impl.FactoryImpl.getOrCreateProxyByName(FactoryImpl.java:522)
	at com.hazelcast.impl.FactoryImpl.getMap(FactoryImpl.java:490)
	at com.hazelcast.impl.FactoryImpl$HazelcastInstanceProxy.getMap(FactoryImpl.java:224)
	at com.hazelcast.core.Hazelcast.getMap(Hazelcast.java:140)
	at edu.ucsb.nceas.metacat.dataone.hazelcast.HazelcastService.init(HazelcastService.java:195)
	at edu.ucsb.nceas.metacat.dataone.hazelcast.HazelcastService.<init>(HazelcastService.java:121)
	at edu.ucsb.nceas.metacat.dataone.hazelcast.HazelcastService.getInstance(HazelcastService.java:141)
	at edu.ucsb.nceas.metacat.MetaCatServlet.initSecondHalf(MetaCatServlet.java:438)
	at edu.ucsb.nceas.metacat.MetaCatServlet.init(MetaCatServlet.java:310)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1173)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:993)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4387)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4700)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:546)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:905)
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:740)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:500)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1061)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
	at org.apache.catalina.core.StandardService.start(StandardService.java:525)
	at org.apache.catalina.core.StandardServer.start(StandardServer.java:701)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:585)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
Caused by: java.lang.NullPointerException
	at java.math.BigInteger.<init>(BigInteger.java:270)
	at java.math.BigInteger.<init>(BigInteger.java:447)
	at edu.ucsb.nceas.metacat.IdentifierManager.getSystemMetadata(IdentifierManager.java:276)
	at edu.ucsb.nceas.metacat.dataone.hazelcast.SystemMetadataMap.load(SystemMetadataMap.java:63)
	... 39 more

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2012-01-03T19:26:08Z

---

It looks like this is due to a null SystemMetadata.size entry in the underlying table. I'm not sure how a null could get in there, unless there was an error when registering the SystemMetadata record.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2012-01-04T19:28:24Z

---

wasn't able to replicate this, but will keep an eye out. There's been quite a lot of churn around the DB tables, so it's possible null values have crept in during development upgrades to the systemMetadata table.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:30:56Z

---

Original Bugzilla ID was 5568
